<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('category')->insert([
            ['id' => 1, 'category_name' => 'Penerbitan & Percetakan', 'category_desc' => 'Suatu usaha atau kegiatan mengelola informasi dan daya imajinasi untuk membuat konten kreatif yang memiliki keunikan tertentu, dituangkan dalam bentuk tulisan, gambar dan/atau audio ataupun kombinasinya, diproduksi untuk dikonsumsi publik, melalui media cetak, media elektronik, ataupun media daring untuk mendapatkan nilai ekonomi, sosial ataupun seni dan budaya yang lebih tinggi', 'category_icon' => 'percetakan.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 2, 'category_name' => 'Teknologi Informasi', 'category_desc' => 'Suatu proses menghasilkan ide atau gagasan agar menghasilkan suatu karya yang memiliki nilai tambah yaitu teknologi sebagai teknik dalam mengumpulkan, memproses, menganalisis, dan/atau menyebarkan informasi untuk memudahkan pengguna saling berinteraksi melalui jaringan komputer', 'category_icon' => 'teknologi.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 3, 'category_name' => 'Permainan Interaktif', 'category_desc' => 'Suatu media atau aktivitas yang memungkinkan tindakan bermain berumpan balik dan memiliki karakteristik setidaknya berupa tujuan (objective) dan aturan (rules)', 'category_icon' => 'permainan.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 4, 'category_name' => 'Musik', 'category_desc' => 'Segala jenis usaha dan kegiatan kreatif  yang berkaitan dengan pendidikan, kreasi/komposisi, rekaman, promosi, distribusi, penjualan, dan pertunjukan karya seni musik', 'category_icon' => 'musik.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 5, 'category_name' => 'Desain', 'category_desc' => 'Proses pemecahan masalah objektif manusia dan lingkungan yang didasari kolaborasi ilmu dan kreativitas dengan menambahkan nilai-nilai termasuk nilai identitas budaya dan nilai tambah (added value) baik secara ekonomis, fungsional, sosial, dan estetika sehingga dapat memberikan solusi subjektif', 'category_icon' => 'desain.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 6, 'category_name' => 'Film, Animasi dan Fotografi', 'category_desc' => 'Video adalah sebuah aktivitas kreatif, berupa eksplorasi dan inovasi dalam cara merekam (capture) atau membuat gambar bergerak, yang ditampilkan melalui media presentasi, yang mampu memberikan karya gambar bergerak alternatif yang berdaya saing dan memberikan nilai tambah budaya, sosial, dan ekonomi', 'category_icon' => 'filmvideo.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 7, 'category_name' => 'Kerajinan', 'category_desc' => 'Bagian dari seni rupa terapan yang merupakan titik temu antara seni dan desain yang bersumber dari warisan tradisi atau ide kontemporer yang hasilnya dapat berupa karya seni, produk fungsional, benda hias dan dekoratif, serta dapat dikelompokkan berdasarkan material dan eksplorasi alat teknik yang digunakan, dan juga dari tematik produknya', 'category_icon' => 'kerajinan.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 8, 'category_name' => 'Seni Rupa', 'category_desc' => 'Penciptaan karya dan saling berbagi pengetahuan yang merupakan manifestasi intelektual dan keahlian kreatif, yang mendorong terjadinya perkembangan budaya dan perkembangan industri dengan nilai ekonomi untuk keberlanjutan ekosistemnya', 'category_icon' => 'senirupa.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 9, 'category_name' => 'Arsitektur', 'category_desc' => 'Wujud hasil penerapan pengetahuan, ilmu, teknologi, dan seni secara utuh dalam menggubah lingkungan binaan dan ruang, sebagai bagian dari kebudayaan dan peradaban manusia sehingga dapat menyatu dengan keseluruhan lingkungan ruang', 'category_icon' => 'arsitek.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 10, 'category_name' => 'Kuliner', 'category_desc' => 'Kegiatan persiapan, pengolahan, penyajian produk makanan dan minuman yang menjadikan unsur kreativitas, estetika, tradisi, dan/atau kearifan lokal; sebagai elemen terpenting dalam meningkatkan cita rasa dan nilai produk tersebut, untuk menarik daya beli dan memberikan pengalaman bagi konsumen', 'category_icon' => 'kuliner.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 11, 'category_name' => 'Mode', 'category_desc' => 'Suatu gaya hidup dalam berpenampilan yang mencerminkan identitas diri atau kelompok.. Mode bukan cuma ada pada pakaian. Mode ada di langit, ada di jalanan, mode berhubungan dengan ide-ide, bagaimana cara kita hidup, apa yang sedang hangat.', 'category_icon' => 'mode.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 12, 'category_name' => 'Periklanan', 'category_desc' => 'Bentuk komunikasi melalui media tentang produk dan/atau merek kepada khalayak sasarannya agar memberikan tanggapan sesuai tujuan pemrakarsa', 'category_icon' => 'iklan.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 13, 'category_name' => 'Seni Pertunjukan', 'category_desc' => 'Cabang kesenian yang melibatkan perancang, pekerja teknis dan penampil (performers), yang mengolah, mewujudkan dan menyampaikan suatu gagasan kepada penonton (audiences); baik dalam bentuk lisan, musik, tata rupa, ekspresi dan gerakan tubuh, atau tarian; yang terjadi secara langsung (live) di dalam ruang dan waktu yang sama, di sini dan kini (hic et nunc)', 'category_icon' => 'pertunjukan.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 14, 'category_name' => 'Penelitian & Pengembangan', 'category_desc' => 'Kegiatan sistematis untuk mengumpulkan, memanfaatkan serta mengolah ilmu pengetahuan dengan tujuan mengonfirmasi dan/atau merancang dan/atau mengembangkan suatu hal (objek penelitian) menjadi hal baru yang lebih baik dan inovatif yang dapat memenuhi kebutuhan pasar dan memberikan manfaat ekonomi', 'category_icon' => 'riset.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 15, 'category_name' => 'Televisi & Radio', 'category_desc' => 'Televisi adalah kegiatan kreatif yang meliputi proses pengemasan gagasan dan informasi dalam bentuk hiburan yang berkualitas kepada penikmatnya dalam format suara dan gambar yang disiarkan kepada publik dalam bentuk virtual secara teratur dan berkesinambungan. Radio adalah kegiatan kreatif yang meliputi proses pengemasan gagasan dan informasi secara berkualitas kepada penikmatnya dalam format suara yang disiarkan kepada publik dalam bentuk virtual secara teratur dan berkesinambungan', 'category_icon' => 'tvradio.png', 'category_parent' => NULL, 'category_type' => 'P', 'category_color' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);
    }
}
