<?php

use Illuminate\Database\Seeder;

class LinksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('links')->insert([
                ['name' => 'adn', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'android', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'angellist', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'apple', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'behance', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'behance square', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'bitbucket', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'bitbucket square', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'bitcoin', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'buysellads', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'codepen', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'connectdevelop', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'dashcube', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'delicious', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'deviantart', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'digg', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'dribbble', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'dropbox', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'drupal', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'empire', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'facebook', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'facebook square', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'flickr', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'forumbee', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'foursquare', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'git', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'git square', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'github alternate', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'github', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'github square', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'gittip', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'google', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'google plus', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'google plus square', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'hacker news', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'instagram', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'ioxhost', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'joomla', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'jsfiddle', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'lastfm', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'lastfm square', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'leanpub', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'linkedin', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'linkedin square', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'linux', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'maxcdn', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'meanpath', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'medium', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'pagelines', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'pied piper alternate', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'pied piper', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'pinterest', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'pinterest square', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'qq', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'rebel', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'reddit', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'reddit square', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'renren', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'sellsy', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'shirtsinbulk', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'simplybuilt', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'skyatlas', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'skype', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'slack', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'slideshare', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'soundcloud', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'spotify', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'stack exchange', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'stack overflow', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'steam', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'steam square', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'stumbleupon circle', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'stumbleupon', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'tencent weibo', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'trello', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'tumblr', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'tumblr square', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'twitch', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'twitter', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'twitter square', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'viacoin', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'vimeo', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'vine', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'vk', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'wechat', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'weibo', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'whatsapp', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'windows', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'wordpress', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'xing', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'xing square', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'yahoo', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'yelp', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'youtube', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'youtube play', 'created_at' => time(), 'updated_at' => time()],
				['name' => 'youtube square', 'created_at' => time(), 'updated_at' => time()]
            ]);
    }
}
