<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class LinksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('links')->insert([
                ['name' => 'adn'],
				['name' => 'android'],
				['name' => 'angellist'],
				['name' => 'apple'],
				['name' => 'behance'],
				['name' => 'behance square'],
				['name' => 'bitbucket'],
				['name' => 'bitbucket square'],
				['name' => 'bitcoin'],
				['name' => 'buysellads'],
				['name' => 'codepen'],
				['name' => 'connectdevelop'],
				['name' => 'dashcube'],
				['name' => 'delicious'],
				['name' => 'deviantart'],
				['name' => 'digg'],
				['name' => 'dribbble'],
				['name' => 'dropbox'],
				['name' => 'drupal'],
				['name' => 'empire'],
				['name' => 'facebook'],
				['name' => 'facebook square'],
				['name' => 'flickr'],
				['name' => 'forumbee'],
				['name' => 'foursquare'],
				['name' => 'git'],
				['name' => 'git square'],
				['name' => 'github alternate'],
				['name' => 'github'],
				['name' => 'github square'],
				['name' => 'gittip'],
				['name' => 'google'],
				['name' => 'google plus'],
				['name' => 'google plus square'],
				['name' => 'hacker news'],
				['name' => 'instagram'],
				['name' => 'ioxhost'],
				['name' => 'joomla'],
				['name' => 'jsfiddle'],
				['name' => 'lastfm'],
				['name' => 'lastfm square'],
				['name' => 'leanpub'],
				['name' => 'linkedin'],
				['name' => 'linkedin square'],
				['name' => 'linux'],
				['name' => 'maxcdn'],
				['name' => 'meanpath'],
				['name' => 'medium'],
				['name' => 'pagelines'],
				['name' => 'pied piper alternate'],
				['name' => 'pied piper'],
				['name' => 'pinterest'],
				['name' => 'pinterest square'],
				['name' => 'qq'],
				['name' => 'rebel'],
				['name' => 'reddit'],
				['name' => 'reddit square'],
				['name' => 'renren'],
				['name' => 'sellsy'],
				['name' => 'shirtsinbulk'],
				['name' => 'simplybuilt'],
				['name' => 'skyatlas'],
				['name' => 'skype'],
				['name' => 'slack'],
				['name' => 'slideshare'],
				['name' => 'soundcloud'],
				['name' => 'spotify'],
				['name' => 'stack exchange'],
				['name' => 'stack overflow'],
				['name' => 'steam'],
				['name' => 'steam square'],
				['name' => 'stumbleupon circle'],
				['name' => 'stumbleupon'],
				['name' => 'tencent weibo'],
				['name' => 'trello'],
				['name' => 'tumblr'],
				['name' => 'tumblr square'],
				['name' => 'twitch'],
				['name' => 'twitter'],
				['name' => 'twitter square'],
				['name' => 'viacoin'],
				['name' => 'vimeo'],
				['name' => 'vine'],
				['name' => 'vk'],
				['name' => 'wechat'],
				['name' => 'weibo'],
				['name' => 'whatsapp'],
				['name' => 'windows'],
				['name' => 'wordpress'],
				['name' => 'xing'],
				['name' => 'xing square'],
				['name' => 'yahoo'],
				['name' => 'yelp'],
				['name' => 'youtube'],
				['name' => 'youtube play'],
				['name' => 'youtube square']
            ]);
    }
}
